name: "${project.artifactId}"
main: "${project.groupId}.${project.artifactId}"
version: "${project.version}"
description: "${project.artifactId} Bukkit Plugin"
author: "BillyGalbreath"
api-version: "1.13"

commands:
  lobby:
    description: lobby
    usage: /<command> (reload | version)
    aliases:
      - test
      - hub

permissions:
  command.lobby:
    description: Allows to reload the configs
    default: op
