name: "${project.artifactId}"
main: "${project.groupId}.${project.artifactId}"
version: "${project.version}"
description: "${project.artifactId} Bukkit Plugin"
author: "Thrasilias"
api-version: "1.13"

commands:
  stub:
    description: stub
    usage: /<command> (reload)
    aliases:
      - test

permissions:
  command.stub:
    description: Allows to reload the configs
    default: op
