name: "${project.artifactId}"
main: "${project.groupId}.${project.artifactId}"
version: "${project.version}"
description: "${project.artifactId} Bukkit Plugin"
author: "Thrasilias"
api-version: "1.13"

commands:
  chat:
    description: chat
    usage: /<command> (reload | version)
    aliases:
      - chat
      - ct
      - chatreload

permissions:
  muniverse.command.chat:
    description: Allows to reload the configs
    default: op
